### ISSUE TITLE
Getting a new token and logging user out

### ISSUE THREAD

**Issue by chrisriner** [microsoftgraph/msgraph-sdk-objc-auth#3]
Is there a way to log the user out after they initially log in and get a token?

Also I am noticing that once I get a token I don't seem to be prompted again to get a token so does that mean it is getting a token silently for me?  Also I deleted the app and installed it again and I was not prompted for Microsoft login to get a new token and the app worked anyway so I don't understand where it was getting the token after I reinstalled.(reinstall meaning I deleted the app and reran the app from Xcode)

**Comment by darrelmiller** [comment]
Hey Chris!  The PublicClientApplication that you pass into the AuthProvider should have a logout method on it.  I'm not that familiar with the ObjC MSAL but that's how it works in the other languages.

**Comment by ricsantos** [comment]
I haven't read the code, but seeing as you are still authenticated after deleting the app and re-installing it, sounds like the auth token/details are being saved to the iOS keychain.
